alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias www='python3 -m http.server $@'
alias gdb='gdb -q'
alias j='john --wordlist=/usr/share/wordlists/rockyou.txt'
alias nmap='nmap --privileged'
alias copy='xclip -selection clipboard'
alias htbvpn='sudo openvpn ~/vpn/HTB/competitive_g0rchy.ovpn'
alias htbrvpn='sudo openvpn ~/vpn/HTB/release_arena_g0rchy.ovpn'
alias thmvpn='sudo openvpn ~/vpn/THM/g0rchy.ovpn'
