# XTerm's default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

# Bright colors
[colors.bright]
black   = '#7f7f7f'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#5c5cff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'

[colors.cursor]
cursor = "#f00000"
text = "CellForeground"

[env]
EDITOR = "vim"
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.7
decorations = "None"
blur = true
dynamic_title = false

[cursor]
style.blinking = "Always"
blink_interval = 500

[mouse]
hide_when_typing = true

[font]
size = 10

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"
